default_platform(:android)

platform :android do
  desc "Build release AAB"
  lane :build do
    gradle(task: "clean bundleRelease")
  end

  desc "Upload to Google Play (internal track)"
  lane :deploy_internal do
    upload_to_play_store(
      track: "internal",
      aab: "android/app/build/outputs/bundle/release/app-release.aab",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end
